### ISSUE TITLE
Reverse engineering

### ISSUE THREAD

**Issue by leomayer** [Leniolabs/layoutit-grid#101]
I love your app and your approach. Currently I see that I can edit the CSS settings and they are taken over.

My current work flow looks like: I'm copy'n-paste the CSS from your side and simply use it in my app. Nevertheless after some time I need to make some changes, e.g. adapt `aligin-self` or add an class. I cannot use your site to reverse engineer the code. I mean that I would love to copy paste back the same code I'm using and than apply some changes.

I see I can make manual changes of the CSS-settings. But I don't see any chance to paste an existing CSS code into the field. 

Honestly I have no clue if this something which could be done easily or if that's some kind of complex change - especially with parse errors. Nevertheless my 2 cents....

**Comment by patak-dev** [comment]
Hey, thanks for your interest! We have discussed an import feature at one point, but as you say it is quite complex to get right. The tool scope is that of a one-way generator and learning tool. If you want a page builder, where you can edit and continue using it, there are better options available. Maybe something like Figma?
