### ISSUE TITLE
Grid lines are not visible when the gap is 0px

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#11]
![image](https://user-images.githubusercontent.com/583075/93935058-541c1d00-fd24-11ea-98dd-15deecb4cbfe.png)

**Comment by dannynpham** [comment]
Can I help with this? I think we would default to 1px whenever the length value is equal to 0?

**Comment by matias-capeletto** [comment]
Hey @dannynpham! I think that is actually a good idea to close this bug. If we use 1px when the value is zero for the Editor, it will at least be functional. +1 for a PR with this change 👍 

After that, we can then open another issue though, labeled *enhancement* instead of *bug* to properly support a gap of zero. Because it will be good to avoid having that extra pixel that modifies a bit how the grid layout behaves. That will involve playing with CSS, maybe just adding another transparent div to each GridCell with a high enough z-index so all these outlines are above the other cells: https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/grid/GridCell.vue#L273. It is more involved though, because we may end up with issues with lines being drawn above other grid areas. Another approach to try is to move the outlines out of the GridCell into a new Component that is drawn after them in the GridEditor. I think that is probably the way to go. 

So, ya, lets do the quick fix so we can push a solution soon. You are welcome to try to tackle it respecting proper grid sizes in another PR later or we see if somebody else can help us 🙌

**Comment by matias-capeletto** [comment]
fixed by @dannynpham with https://github.com/Leniolabs/layoutit-grid/pull/29
