### ISSUE TITLE
Spaces in grid names

### ISSUE THREAD

**Issue by AlexNodex** [Leniolabs/layoutit-grid#17]
If you add a space to a grid area name the class it generates has a space in it which is invalid css.

i/e if I name my area "foo bar" it generates the css...

`.foo bar { grid-area: foo bar; }`

...which is obiously invalid for this because "bar" would be an element seelctor!

Maybe kebab-case the inputs?

Edit: It seems you already kebab-case the grid-area name inside the `grid-template-areas` it's just missing from the generated CSS.

**Comment by matias-capeletto** [comment]
Thanks for the report @AlexNodex! Yes, looks like a regression when we made the Code interactive, it should be easy to fix.
We also discussed not long ago about capturing spaces and automatically converting them to dashes everywhere for area names, what do you think?
