### ISSUE TITLE
Improve mobile UX to open and close sidebars

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#18]
There should be at least two buttons, one for the Props sidebar and one for the Code and clear hints of how they work. Maybe we need a small header in mobile instead of showing the grid covering the whole screen.

**Comment by gm1357** [comment]
Is there anyone on this? Can I tackle it?

**Comment by agustin-capeletto-lenio** [comment]
@gm1357 go ahead! Let us know if you need help. I think having two buttons for Props/Code is fine for now, in the future we could merge the two sidebars on mobile.

**Comment by gm1357** [comment]
Thanks @agustin-capeletto-lenio. Will work on the two button strategy then.

**Comment by matias-capeletto** [comment]
Thanks @gm1357 ! 🙌
