### ISSUE TITLE
Support exporting to CodeSandbox

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#2]
We can use CodeSandbox Define API to create vanilla sandboxes:

   https://codesandbox.io/docs/api#define-api

I think that people will prefer one of the options (Codepen, CodeSanbox, later other options?), and only use that one when using the app. There should be a way to select this preference and save it in local storage. Only one Export button will be shown in this way avoiding cluttering the UI

**Comment by edades** [comment]
Hi @matias-capeletto do you have in mind a place to have the user preferences and store this selection (codesandbox exportation)?
Also, I think that maybe for now we could have a dropdown to select how to export the code.
Export using: [Dropdown menu]
                          - Codepen
                          - CodeSandbox

thank you

**Comment by matias-capeletto** [comment]
Hey @edades! I think that we can divide this issue in several PRs. If you would like to tackle the CodeSandbox export, we can leave the UI quite simple at first. Just another button next to the current one. We can later see how to improve it.
But if you want to do some UI work also, maybe in a different PR, I think that a good solution is a Split button dropdown. That has the current preferred place to do the export as the main button. And you can click on the arrow next to it to change it. We can also persist this using local storage like we are doing with the dark theme.

**Comment by matias-capeletto** [comment]
Thanks @edades 🎉
