### ISSUE TITLE
Please add the recommended editor config rules to follow 

### ISSUE THREAD

**Issue by centrodph** [Leniolabs/layoutit-grid#25]
https://github.com/vuejs/eslint-plugin-vue/blob/master/.editorconfig

**Comment by matias-capeletto** [comment]
+1, PRs accepted! ❤️

**Comment by alexrobaina** [comment]
@patak-js this issue can be closed?

**Comment by patak-js** [comment]
Hey @alexrobaina, we still need to add .editorconfig. PR welcome!

**Comment by alexrobaina** [comment]
Hi @patak-js! 
Great! Thank you for your answer

I created a PR with .editorconfig 
https://github.com/Leniolabs/layoutit-grid/pull/96
