### ISSUE TITLE
Add copy to clipboard button in code views

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#33]
We can use useClipboard from vueuse https://vueuse.js.org/?path=/story/browser--useclipboard

**Comment by rhythm1920** [comment]
Can I take up this issue for Hacktoberfest??
I am assuming that you want separate button for html and css code. Please inform me if I am wrong in this assumption.   
Some questions before I start working-
* Where should the button be placed? bottom right or  bottom left in the code views or any other position??
* Can I give the same styling and response as the permanent link button??

**Comment by SpaceBuckets** [comment]
Sure @rhythm1920! Feel free to work on this issue :)

As for the design, we just need a "Copy" text on the top right of each code box, aligned with the CSS/HTML titles. When you click on it the text changes to "Copied!".

**Comment by agustin-capeletto-lenio** [comment]
Sure @rhythm1920! Feel free to work on this issue :) 

As for the design, we just need a "Copy" text on the top right of each code box, on the opposite side of the HTML/CSS titles. When you click on it the text changes to "Copied!" temporarily.

**Comment by matias-capeletto** [comment]
@rhythm1920 we have these two computed variables `cssCode` and `htmlCode` that have the code strings we use for the Codepen export and you could pass to the code editors: https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/code/LiveCode.vue#L47

**Comment by rhythm1920** [comment]
I have started working on the issue. I just wanted to know if I should create a separate vue file like `saveButton.vue` or should I add it in the `CodeEditor.vue`. https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/code/CodeEditor.vue

**Comment by matias-capeletto** [comment]
Hey @rhythm1920, both options are fine. But +1 if you want to create a new component. In that case, please use `<script setup>` for it and you could name it something like CodeClipboardButton.vue 👍

**Comment by rhythm1920** [comment]
@matias-capeletto, I have submitted the PR #42. Please review it.

**Comment by matias-capeletto** [comment]
Closing! Thanks again @rhythm1920 🙌
