### ISSUE TITLE
Area name should be editable in the html editor

### ISSUE THREAD

**Issue by patak-js** [Leniolabs/layoutit-grid#35]
We could rename the CssCodeAreaName component to CodeAreaName so we can also use it in the class name of each div

**Comment by ranjal007** [comment]
Is this issue opened? I want to contribute in it for Hacktoberfest,

**Comment by ranjal007** [comment]
I have created a Pull request regarding this issue. Kindly review it @matias-capeletto .

**Comment by matias-capeletto** [comment]
Hey @ranjal007, lets discuss there 👍. 
The rename part is to be able to also use it in the HtmlCodeEditor for the area names in the class attr value.
