### ISSUE TITLE
Add keyboard shortcuts for main features (undo, redo, delete area)

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#37]
We should add keyboard shortcuts for the main actions:
  Cmd+z : undo
  Cmd+y | Cmd+Shift+z : redo
  Cmd+s : Get Permalink
  Cmd+q : reset

When selecting grid cells for a new area (AreaSelection.vue)
  Esc: closes selection, or cancels area edition

When area is active
  delete : removes the area (or the subgrid if there is one)
  c: add column (in the future it can mean, add it where I have the mouse)
  r: add row
  g: add subgrid in the area

**Comment by CodeSadhu** [comment]
Interesting. Would like to take this up. Can you please assign this to me? @matias-capeletto

**Comment by matias-capeletto** [comment]
Totally @CodeSadhu ! That was fast 💯

**Comment by matias-capeletto** [comment]
Hey @CodeSadhu, are you still interested in this feature? I'll remove the assignment if not so others are free to work on it.

**Comment by CodeSadhu** [comment]
@matias-capeletto Damn, sorry. I've been a bit busy lately so it's cool with me if you assign this to someone else. I don't think I'll be able to do this feature right now! Sorry for keeping you hanging 😓

**Comment by matias-capeletto** [comment]
@CodeSadhu no worries! Just checking the state of the issues so people can jump in if they want. Thanks for your interest!

**Comment by erickgomez28** [comment]
Hi @matias-capeletto, I would like to add this feature, could you please assign it to me?

**Comment by matias-capeletto** [comment]
Awesome @erickgomez28 ! Thanks a lot 🙌🏼

**Comment by erickgomez28** [comment]
Hi @matias-capeletto , I can't modify the shortcut to cmd + q because it allows to exit the current application on mac, so I can't catch it with the listener. Could we use another shortcut to reset the grid, maybe cmd + r?

**Comment by matias-capeletto** [comment]
Yes, go for it 👍🏼
