### ISSUE TITLE
Selecting "auto" leads to wrong css 

### ISSUE THREAD

**Issue by amaury-hanser** [Leniolabs/layoutit-grid#43]
Hello, 
Selecting **"auto"** as the value of a column/row generates incorrect css: `1auto` instead of `auto`.

**Steps to reproduce:**

- Go to [https://grid.layoutit.com/](Layoutit!)
- Select **"auto"** for the first column

**Generated css:**

```
.grid-container {
  display: grid;
  grid-template-columns: 1auto 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr;
  gap: 0px 0px;
  grid-template-areas:
    ". . . ."
    ". . . ."
    ". . . .";
}
```

**Expected css:**

```
.grid-container {
  display: grid;
  grid-template-columns: auto 1fr 1fr 1fr; // difference is here
  grid-template-rows: 1fr 1fr 1fr;
  gap: 0px 0px;
  grid-template-areas:
    ". . . ."
    ". . . ."
    ". . . .";
}
```

**Comment by amaury-hanser** [comment]
@matias-capeletto Sorry, I failed to find it. Thanks.

**Comment by matias-capeletto** [comment]
No, thanks you a lot for the report @amaury-hanser! And thanks for looking into it also 💯 
There are more issues open if you want to keep digging 👍 

Looks like there was a regression. `min-content` and `max-content` were also affected.
I took the opportunity and improved the handling of these units overall. The sidebar inputs are just not visible now, and in the view the track sizes are forced to regular values (this is only for the view) so we do not get a 0 size track like before. I think we can improve it later, once we have some way to add content for better previewing the result

You can check it live in https://grid.layoutit.com/, (the version in the sidebar needs to read `1.2.3`)

![image](https://user-images.githubusercontent.com/583075/94910260-c4edd280-04a4-11eb-8452-870d847221d2.png)

Would you mind testing it and reporting back if you find other issues?
Thanks again!

**Comment by amaury-hanser** [comment]
I like the changes you've made!
If I find anything, I'll let you know!
