### ISSUE TITLE
Properly setup eslint and prettier with vite

### ISSUE THREAD

**Issue by matias-capeletto** [Leniolabs/layoutit-grid#48]
We lost this configuration when we migrated to Vite from vue-cli. 

This was the old package.json bits related to this
```
  "devDependencies": {
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "lint-staged": "^9.0.0",
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.js": [
      "vue-cli-service lint",
      "git add"
    ],
    "*.vue": [
      "vue-cli-service lint",
      "git add"
    ]
  }
```

Looks like we now would have to do something like this though:

https://simohamed.tech/blog/vue3-lint/
https://www.simonwuyts.com/articles/vue-3-a-modern-setup-that-will-save-you-time/

**Comment by centrodph** [comment]
@matias-capeletto could you assign me this issue?

**Comment by matias-capeletto** [comment]
Closed with https://github.com/Leniolabs/layoutit-grid/pull/49 by @centrodph ❤️
