### ISSUE TITLE
api-save- recovery

### ISSUE THREAD

**Issue by adyuebanwan** [Leniolabs/layoutit-grid#57]
hi, how to save and recovery data by api?  (use json)
for example:
saveDesign(data){
....
}
recovery(data){

}

can you give me some cases ,Thanks!

**Comment by matias-capeletto** [comment]
Hello @adyuebanwan, what is your use case?
We will add support to persist the current layout after reloading the page soon, and to do that we will have to convert the current state to json for local storage. We have another serialization version that is used for the permalink feature, but that is only available in the deployed app right now.

**Comment by matias-capeletto** [comment]
I think with time we should follow the lead of https://excalidraw.com/ in this regard, they have a lot of good ideas about saving and recovering. They even support direct save and load from the filesystem.
