### ISSUE TITLE
[Feature Request] Import Previously Generated Grids

### ISSUE THREAD

**Issue by karatetoes** [Leniolabs/layoutit-grid#64]
Had a Windows update during my layoutit grid making and lost all the grid elements I had designated.  It would be amazing to me and my future work if I was able to import previously generated layoutit grids

**Comment by matias-capeletto** [comment]
Hey @karatetoes, thanks for your feedback. I totally agree, and the feature you are requesting is currently implemented together with a lot of new goodies. We plan to release the new version soon (hopefully in just a few weeks). We will be tweeting about the new features at https://twitter.com/layoutit
