### ISSUE TITLE
paste in existing grid-template-areas "header header header", etc to generate IE 10 / IE 11 legacy grid specs

### ISSUE THREAD

**Issue by overtheover** [Leniolabs/layoutit-grid#66]
It would be extremely helpful if you had an additional textbox where I could paste in the code for grid-template-areas and have it output the correct IE 10 / IE 11 CSS for -ms-grid-row, -ms-grid-row-span, -ms-grid-column, -ms-grid-column-span, etc for grid-template-areas.

Creating the grid is easy enough visually in grid-template-areas - but trying to make it work in IE 10 / 11 is mind numbing.

**Comment by matias-capeletto** [comment]
Thanks for the suggestion. I think that it could be a nice standalone tool, I wonder if there isn't one already on the web.
For this app, I think It is not that easy to implement because we would need both HTML and CSS to be pasted, or maybe load from a CodePen. It could be interesting to explore.
