### ISSUE TITLE
Unable to click on sidebar elements on lower portion of smaller screens

### ISSUE THREAD

**Issue by leandroercoli** [Leniolabs/layoutit-grid#75]
On smaller screens, some elements in the sidebar become unreachable when the mobile buttons' wrapper is displayed on top.

<img width="1431" alt="sidebar-mobile-bug-v1" src="https://user-images.githubusercontent.com/26791103/118279553-a8396480-b4a1-11eb-895c-b54eaa287ff4.png">
<img width="1258" alt="sidebar-mobile-bug-v2" src="https://user-images.githubusercontent.com/26791103/118279574-ac658200-b4a1-11eb-9f6a-db3af71b17b8.png">

**Comment by patak-js** [comment]
I agree the mobile experience can be improved. Ideas and PRs welcome :)

**Comment by patak-js** [comment]
Closing as resolved, thanks again for your contribution @leandroercoli
