### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by ghostdevv** [Leniolabs/layoutit-grid#91]
Would be great to have a reset button, whenever I am done with a big grid it's a pain to have to manually clear it all to start a fresh

**Comment by patak-js** [comment]
There is a Restart button in the top right corner 👍🏼 
![image](https://user-images.githubusercontent.com/583075/127867945-49f5ffa5-9f63-4e00-be59-a2c292d494ea.png)

**Comment by ghostdevv** [comment]
Awesome, I missed that :sweat_smile:

**Comment by patak-js** [comment]
Maybe we should change the icon, would something like this icon be more clear to you?
![image](https://user-images.githubusercontent.com/583075/127878541-af4ceb47-780f-4589-97ff-ebe55394a0ae.png)

**Comment by patak-js** [comment]
Oh... but smaller, github filled up the whole comment 😅

**Comment by ghostdevv** [comment]
Definitely too big xD
![](https://i.imgur.com/m5cbBAf.png)

It's fine how it is, I just didn't notice it was there - been using v1 for a while so still getting used to the new version's ui

**Comment by patak-js** [comment]
hahaha, PR welcome with that icon 😄

What do you think about the new UI? We were worried about changing too much. Very interested if you have any feedback on the new features, easy of use, design.

We also left v1 at https://grid-v1.layoutit.com just in case, but I hope that most people will prefer the new version

**Comment by ghostdevv** [comment]
> hahaha, PR welcome with that icon smile
Might do

> What do you think about the new UI? We were worried about changing too much. Very interested if you have any feedback on the new features, easy of use, design.
It has a lot of stuff that v1 was missing, so the update is awesome. There is only one thing that wasn't obvious, and that is if you double click on a item inside grid placement it resets it back to inital, at first I was wondering how to do that - other than that it's awesome. I use this tool all the time!

> We also left v1 at https://grid-v1.layoutit.com just in case, but I hope that most people will prefer the new version
While getting used to the UI I did use this a few times to quickly create simple grids - it would be great if you can add a place to switch back to v2 on the v1 site like you can on the v2 site

**Comment by patak-js** [comment]
> > hahaha, PR welcome with that icon smile
> 
> Might do

Just in case, that was just a random icon. We are using this set https://holasvg.com/icons from @marianabeldi, but we may need to talk with her about adding or modifying the reset one. IMO it could be more clear.
But other PRs are more than welcome :)

> > What do you think about the new UI? We were worried about changing too much. Very interested if you have any feedback on the new features, easy of use, design.
> 
> It has a lot of stuff that v1 was missing, so the update is awesome. There is only one thing that wasn't obvious, and that is if you double click on a item inside grid placement it resets it back to inital, at first I was wondering how to do that - other than that it's awesome. I use this tool all the time!

Oh... I see that we have zero feedback for that one. Maybe the color should change on hover once it is selected so you know that something would happen if you press it.

> > We also left v1 at [grid-v1.layoutit.com](https://grid-v1.layoutit.com) just in case, but I hope that most people will prefer the new version
> 
> While getting used to the UI I did use this a few times to quickly create simple grids - it would be great if you can add a place to switch back to v2 on the v1 site like you can on the v2 site

Ya, that would be nice 👍🏼

**Comment by ghostdevv** [comment]
Sounds good!

**Comment by patak-js** [comment]
I also think that when you get back to initial, the picker shouldn't close the other options.

**Comment by patak-js** [comment]
Thanks for the feedback, issue to track the picker improvements here https://github.com/Leniolabs/layoutit-grid/issues/92
