### ISSUE TITLE
Changes of width are not transferred to CSS

### ISSUE THREAD

**Issue by leomayer** [Leniolabs/layoutit-grid#97]
I want to change the width of a column, e.g. from the default of `4em` to `8em`. The changes are not reflected in the CSS. 

After change of the focus the initial values are still displayed.

I made a short [video](https://drive.google.com/file/d/1HMgUBkUREq-dfhQ9aykuSbhjjTJY1ooS/view?usp=sharing) how this works.

**Comment by patak-js** [comment]
Thanks for the report! Could you refresh the app and test it now?

**Comment by leomayer** [comment]
After a quick test it seems to work. Thx
