### ISSUE TITLE
Sizes go back to defaults

### ISSUE THREAD

**Issue by bartrylant** [Leniolabs/layoutit-grid#98]
Might be the same issue as this one:
https://github.com/Leniolabs/layoutit-grid/issues/97

When I enter some values in the grid sizes input fields, they just go back to their initial state. E.g.:

- I set the width to pixels
- Default is 300 wide
- I change 300 to 100
- I click somewhere else or tab
- Width changes back to 300

**Comment by patak-js** [comment]
Thanks for the report, and sorry for the glitch. Please refresh the app, it should work now 👍🏼
Closed by https://github.com/Leniolabs/layoutit-grid/commit/61208a3de8f7bc0dac7b0f1a81cee41a469a82c8
